services:
  - type: web
    name: car-price-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
